# Generated by Django 2.2 on 2020-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedSong',
            fields=[
                ('hash_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date loaded')),
                ('input_url', models.URLField()),
                ('vocal_url', models.URLField()),
                ('accompaniment_url', models.URLField()),
            ],
        ),
    ]
