# Generated by Django 2.2 on 2020-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_access_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogsmodel',
            name='processed_time',
            field=models.DurationField(blank=True),
        ),
    ]
